POST http://localhost:8000/api/v1/units-of-measure/create
Content-Type: application/json
Accept: application/json

{"name": "Kilogram", "symbol": "Kg", "unitOfMeasureType": 0}

###
POST http://localhost:8000/api/v1/units-of-measure/create
Content-Type: application/json
Accept: application/json

{"name": "LitreXXX", "symbol": "lx", "unitOfMeasureType": 1}
