GET http://localhost:8000/api/v1/users/b68c9bc2-0c4d-4136-b738-711e920ce47a
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3OTAzMTQxMTMsImV4cCI6MTc5MDMxNzcxMywicm9sZXMiOlsiUk9MRV9TVVBFUl9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImdvZC5oaW1zZWxmQGhlYXZlbi5vcmcifQ.oqgLRnF1rux3JbEEyEG7oJ5D-1V5-e87ZWmheGO_pu4HFpqABFmGSd-g2wW7VIxXHPS9fNPgzO9Qa8BqgdyNiboO7nmG3WtHo4NJnUGat7i1qWd26rW4uFKHsYf9jYcA5nrDK_whxQNcYa_KTvIAjWgnPz_34ghEE9Ey5bkzjVpdcJNcG0uzHDvTrtBcLnMVGaIgRI-Jyy3ZJxoosJyux_FQpF2ZdZ8AkHXp6YfzBASxOdhJVUsIs845q6F0vi68vkis50-5R1ZfAbj9eYcbwSQ-NhzHmpDLyaTfXWRfAvmD_2SEazJm_ic6YfZFKb4UHDPowj_uRNjTwgZxfUrufQ
