PUT http://localhost:8000/api/v1/users/b68c9bc2-0c4d-4136-b738-711e920ce47a
Content-Type: application/json

{
    "email": "test@test1.com",
    "password": "lolo",
    "firstName": "test",
    "lastName": "more test",
    "roles": "ROLE_USER"
}
