POST http://localhost:8000/api/v1/recipes/create
Content-Type: application/json

{
    "name": "A recipe with empty steps",
    "description": "Some description with empty steps",
    "source": "Some source with empty steps",
    "rating": 2,
    "servings": 2,
    "steps": []
}

###

POST http://localhost:8000/api/v1/recipes/create
Content-Type: application/json

{
    "name": "Another recipe with some steps",
    "description": "Some description with some steps",
    "source": "Some source with some steps",
    "rating": 2,
    "servings": 2,
    "steps": [
        {
            "description": "This is the first step in the recipe.",
            "ordering": 1
        },
        {
            "description": "This is the second step in the recipe.",
            "ordering": 2
        }
    ]
}

###
# Should fail, 400 Bad request
POST http://localhost:8000/api/v1/recipes/create
Content-Type: application/json

{
    "name": "A recipe",
    "description": "Some description",
    "source": "Some source",
    "rating": "xxx",
    "servings": "4"
}

###
# Should fail, 400 Bad request
POST http://localhost:8000/api/v1/recipes/create
Content-Type: application/json

{
    "name": "A recipe",
    "description": "Some description",
    "source": "Some source",
    "rating": "4",
    "servings": "xxxx"
}

###
# Should fail, 400 Bad request (name removed)
POST http://localhost:8000/api/v1/recipes/create
Content-Type: application/json

{
    "description": "Some description",
    "source": "Some source",
    "rating": "4",
    "servings": "3"
}
