### Change ID. Should Work!
DELETE http://localhost:8000/api/v1/recipes/f287e4d6-bea1-4a6b-942d-f5845b6138a2
Accept: application/json

### Should fail, 404 Not found
DELETE http://localhost:8000/api/v1/recipes/f287e4d6-bea1-4a6b-942d-f5845b6138a2
Accept: application/json

### Should fail, 400 Bad request
DELETE http://localhost:8000/api/v1/recipes/00000000-0000-0000-0000-000000000000
Accept: application/json
