### Should fail, 404 Not found
DELETE http://localhost:8000/api/v1/recipes/cabc5a22-15f8-4b8e-b22c-5581e02533a3
Accept: application/json

### Should fail, 400 Bad request
DELETE http://localhost:8000/api/v1/recipes/00000000-0000-0000-0000-000000000000
Accept: application/json
