### 200
GET http://localhost:8000/api/v1/recipes/e68a3da9-f163-4adb-bed1-45eab1e9e3ac
Accept: application/json

### 200, with some steps
GET http://localhost:8000/api/v1/recipes/1d916354-4a36-48c6-bc09-e97fa1a84414
Accept: application/json

### Should fail, 404 Not found
GET http://localhost:8000/api/v1/recipes/2481d2d0-08c6-4ab1-a235-a5598d3af6e6
Accept: application/json

### Should fail, 400 Bad request
GET http://localhost:8000/api/v1/recipes/00000000-0000-0000-0000-000000000000
Accept: application/json
