PUT http://localhost:8000/api/v1/recipes/e68a3da9-f163-4adb-bed1-45eab1e9e3ac
Content-Type: application/json

{
    "name": "An updated recipe name",
    "description": "Some updated description",
    "source": "Some updated source",
    "rating": "2",
    "servings": "14"
}

###
# Should fail, 404 not found

PUT http://localhost:8000/api/v1/recipes/2481d2d0-08c6-4ab1-a235-a5598d3af6e6
Content-Type: application/json

{
    "name": "An updated recipe name",
    "description": "Some updated description",
    "source": "Some updated source",
    "rating": "2",
    "servings": "14"
}

###
# Should fail, 400 bad request

PUT http://localhost:8000/api/v1/recipes/00000000-0000-0000-0000-000000000000
Content-Type: application/json

{
    "name": "An updated recipe name",
    "description": "Some updated description",
    "source": "Some updated source",
    "rating": "2",
    "servings": "14"
}

###
# Should fail, 400 bad request
# name missing
PUT http://localhost:8000/api/v1/recipes/e68a3da9-f163-4adb-bed1-45eab1e9e3ac
Content-Type: application/json

{
    "description": "Some updated description",
    "source": "Some updated source",
    "rating": "2",
    "servings": "14"
}
