PUT http://localhost:8000/api/v1/recipes/e68a3da9-f163-4adb-bed1-45eab1e9e3ac
Content-Type: application/json

{
    "name": "An updated recipe name",
    "description": "Some updated description",
    "source": "Some updated source",
    "rating": 2,
    "servings": 14,
    "steps": [],
    "ingredients": []
}

###
# Should fail, 404 not found

PUT http://localhost:8000/api/v1/recipes/2481d2d0-08c6-4ab1-a235-a5598d3af6e6
Content-Type: application/json

{
    "name": "An updated recipe name",
    "description": "Some updated description",
    "source": "Some updated source",
    "rating": 2,
    "servings": 14,
    "steps": [],
    "ingredients": []
}

###
# Should fail, 400 bad request

PUT http://localhost:8000/api/v1/recipes/00000000-0000-0000-0000-000000000000
Content-Type: application/json

{
    "name": "An updated recipe name",
    "description": "Some updated description",
    "source": "Some updated source",
    "rating": 2,
    "servings": 14
}

###
# Should fail, 400 bad request
# name missing
PUT http://localhost:8000/api/v1/recipes/e68a3da9-f163-4adb-bed1-45eab1e9e3ac
Content-Type: application/json

{
    "description": "Some updated description",
    "source": "Some updated source",
    "rating": "2",
    "servings": "14"
}

###
# Update
PUT http://localhost:8000/api/v1/recipes/52f21dfa-f344-42c9-afb8-31ed79379dc0
Content-Type: application/json

{
    "name": "some updated name",
    "description": "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "source": "Some updated source",
    "rating": 2,
    "servings": 5,
    "steps": [
        {
            "id": "4a1bcd69-c871-4d97-8aee-3262f3c30590",
            "description": "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY",
            "ordering": 1
        },
        {
            "id": "c10cc649-ca68-4240-8bee-d8cbacbcee6d",
            "description": "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ",
            "ordering": 2
        }
    ],
    "ingredients": []
}

###
# Update
PUT http://localhost:8000/api/v1/recipes/d4b56772-aac4-4826-8205-6e68a590ff70
Content-Type: application/json

{
    "name": "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "description": "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "source": "Some updated source",
    "rating": 2,
    "servings": 5,
    "steps": [
        {
            "id": "4a1bcd69-c871-4d97-8aee-3262f3c30590",
            "description": "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY",
            "ordering": 1
        },
        {
            "id": "c10cc649-ca68-4240-8bee-d8cbacbcee6d",
            "description": "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ",
            "ordering": 2
        }
    ],
    "ingredients": [
        {
            "id": "54e52139-8206-429d-9aff-15195b581c5e",
            "ingredientId": "fc066bb1-22a9-47a4-981d-81f5065b461f",
            "unitOfMeasureId": "647bfd95-ba44-47bd-a745-2a7b4e9c055b",
            "quantity": 99,
            "ordering": 3
        }
    ]
}
