POST http://localhost:8000/api/v1/ingredients/create
Content-Type: application/json

{
    "name": "An ingredient do delete",
    "description": "XXXXXXXX",
    "ingredientTypeId": "84d77bf6-43d6-4d4e-b559-3a203e750eeb"
}

###

DELETE http://localhost:8000/api/v1/ingredients/5576c1b2-9c04-473e-ae88-34ec7855ba9f
Accept: application/json
