POST http://localhost:8000/api/v1/ingredients/create
Content-Type: application/json

{
    "name": "An ingredient do delete",
    "description": "XXXXXXXX",
    "ingredientTypeId": "84d77bf6-43d6-4d4e-b559-3a203e750eeb"
}

###

DELETE http://localhost:8000/api/v1/ingredients/3fde0d93-38eb-425c-a763-0d802b9cfc55
Accept: application/json

###
# 2nd run will fail, 404

DELETE http://localhost:8000/api/v1/ingredients/1baf32a2-b176-4070-a142-416af3c2aa1e
Accept: application/json
