###
# Should return 200
GET http://localhost:8000/api/v1/ingredients?offset=0
Accept: application/json

###
# Should fail
GET http://localhost:8000/api/v1/ingredients?offset=0&limit=1000
Accept: application/json
