GET http://localhost:8000/api/v1/ingredients/fc066bb1-22a9-47a4-981d-81f5065b461f
Accept: application/json

###
# Expected to fail: id is not an Uuid
GET http://localhost:8000/api/v1/ingredients/abcde
Accept: application/json
